services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '3000:3000'
      - '3001:3001'
    networks:
      - app-network
    environment:
      NODE_ENV: production

networks:
  app-network:
    driver: bridge
