name: Build and Publish Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase variables
        run: |
          echo "lowercase_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "lowercase_repo=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Docker Image to GHCR
        run: |
          docker buildx build \
            --push \
            --tag ghcr.io/${{ env.lowercase_owner }}/${{ env.lowercase_repo }}:latest \
            --tag ghcr.io/${{ env.lowercase_owner }}/${{ env.lowercase_repo }}:${{ github.sha }} \
            .
