name: Build and Publish Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ghcr.io/${{ github.repository_owner }}/rtu-cryptochatapp:latest \
            --tag ghcr.io/${{ github.repository_owner }}/rtu-cryptochatapp:${{ github.sha }} \
            .

      - name: Pull and Test Docker Image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/rtu-cryptochatapp:latest
          docker run -d --rm -p 3000:3000 ghcr.io/${{ github.repository_owner }}/rtu-cryptochatapp:latest
