name: Test

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test
